Repository: plone.app.content


Branch: refs/heads/master
Date: 2019-08-28T11:56:04-03:00
Author: Franco Pellegrini (frapell) <frapell@gmail.com>
Commit: https://github.com/plone/plone.app.content/commit/2c07df005b365c6f46719aa962c3c90791961d82

BUGFIX: self.errors is a list, so .append() should be used

Files changed:
M plone/app/content/browser/contents/rename.py

b"diff --git a/plone/app/content/browser/contents/rename.py b/plone/app/content/browser/contents/rename.py\nindex db61450..8e76ec1 100644\n--- a/plone/app/content/browser/contents/rename.py\n+++ b/plone/app/content/browser/contents/rename.py\n@@ -71,7 +71,7 @@ def __call__(self):\n             obj = brains[0].getObject()\n             title = self.objectTitle(obj)\n             if not mtool.checkPermission('Copy or Move', obj):\n-                self.errors(_(u'Permission denied to rename ${title}.',\n+                self.errors.append(_(u'Permission denied to rename ${title}.',\n                               mapping={u'title': title}))\n                 continue\n \n"

