Repository: plone.volto


Branch: refs/heads/main
Date: 2021-10-25T12:38:08+02:00
Author: Timo Stollenwerk (tisto) <stollenwerk@kitconcept.com>
Commit: https://github.com/plone/plone.volto/commit/54c70c8abcb0c7d7ff5e02080b0d845cb0ea7f50

Add error message when using Python 3.6

Files changed:
M setup.py

b'diff --git a/setup.py b/setup.py\nindex 44b1552..6cdf157 100644\n--- a/setup.py\n+++ b/setup.py\n@@ -3,6 +3,10 @@\n \n from setuptools import find_packages\n from setuptools import setup\n+import sys\n+\n+\n+assert sys.version_info >= (3, 6, 0), "plone.volto requires Python 3.7.0."\n \n \n def readfile(name):\n'

